namespace DungeonWorld.Game.Map.Extensions;

public static class FieldMapGeneratorExtension
{
    public static void GenerateLevel(this Field field)
    {
        field.LoadMap([
            new('*', new(-5,-5)),
            new('*', new(-5,-4)),
            new('*', new(-5,-3)),
            new('*', new(-5,-2)),
            new('*', new(-5,-1)),
            new('*', new(-5,0)),
            new('*', new(-5,1)),
            new('*', new(-5,2)),
            new('*', new(-5,3)),
            new('*', new(-5,4)),
            new('*', new(-5,5)),

            new('*', new(5,5)),
            new('*', new(4,5)),
            new('*', new(3,5)),
            new('*', new(2,5)),
            new('*', new(1,5)),
            new('*', new(0,5)),
            new('*', new(-1,5)),
            new('*', new(-2,5)),
            new('*', new(-3,5)),
            new('*', new(-4,5)),
            new('*', new(-5,5)),
            new('*', new(5,-5)),

            new('*', new(5,-5)),
            new('*', new(4,-5)),
            new('*', new(3,-5)),
            new('*', new(2,-5)),
            new('*', new(1,-5)),
            new('*', new(0,-5)),
            new('*', new(-1,-5)),
            new('*', new(-2,-5)),
            new('*', new(-3,-5)),
            new('*', new(-4,-5)),
            new('*', new(-5,-5)),

            new('*', new(5, -4)),
            new('*', new(5, -3)),
            new('*', new(5, 4)),
            new('*', new(5, 3)),

            new('*', new(6, -3)),
            new('*', new(7, -3)),
            new('*', new(8, -3)),
            new('*', new(9, -3)),
            new('*', new(10, -3)),
            new('*', new(11, -3)),
            new('*', new(12, -3)),
            new('*', new(13, -3)),
            new('*', new(14, -3)),
            new('*', new(15, -3)),
            new('*', new(16, -3)),
            new('*', new(17, -3)),
            new('*', new(18, -3)),
            new('*', new(19, -3)),
            new('*', new(20, -3)),

            new('*', new(6, 3)),
            new('*', new(7, 3)),
            new('*', new(8, 3)),
            new('*', new(9, 3)),
            new('*', new(10, 3)),
            new('*', new(11, 3)),
            new('*', new(10, 3)),
            new('*', new(11, 3)),
            new('*', new(12, 3)),
            new('*', new(13, 3)),
            new('*', new(14, 3)),
            new('*', new(15, 3)),
            new('*', new(16, 3)),
            new('*', new(17, 3)),
            new('*', new(18, 3)),
            new('*', new(19, 3)),
            new('*', new(20, 3)),
        ]);
    }
}